name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set environment variables
      run: |
        echo "ID_INSTANCE=${{ secrets.ID_INSTANCE }}" >> $GITHUB_ENV
        echo "API_TOKEN_INSTANCE=${{ secrets.API_TOKEN_INSTANCE }}" >> $GITHUB_ENV

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
